name: CI

on:
  push:
     branches: main
     
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checout@ov
       - name:  Run one line script 
         run: echo Hello world Aidana !!
        
     
